'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import OfficeHeader from '@/components/OfficeHeader';
import OfficeSidebar from '@/components/OfficeSidebar';
import { ArrowRight, CheckCircle2, ClipboardList, FileText, Settings2 } from 'lucide-react';

const moduleCatalog: Record<string, { title: string; section: string; description: string; status: string; links: Array<{ label: string; href: string; detail: string }> }> = {
  bureaux: { title: 'Bureaux', section: 'Organisation administrative', description: 'Préparez la gestion des bureaux rattachés aux divisions et aux services.', status: 'Référentiel à compléter', links: [{ label: 'Gérer les divisions', href: '/divisions', detail: 'Structure hiérarchique actuelle' }, { label: 'Gérer les services', href: '/services', detail: 'Services et rattachements' }] },
  organigramme: { title: 'Organigramme', section: 'Organisation administrative', description: 'Visualisez la structure des directions, divisions et services.', status: 'Vue structurelle', links: [{ label: 'Directions', href: '/directions?tab=list', detail: 'Consulter les directions' }, { label: 'Divisions', href: '/divisions', detail: 'Consulter les divisions' }, { label: 'Services', href: '/services', detail: 'Consulter les services' }] },
  territoires: { title: 'Territoires', section: 'Organisation territoriale', description: 'Espace réservé au référentiel des territoires administratifs.', status: 'Référentiel à compléter', links: [{ label: 'Villes', href: '/villes', detail: 'Niveaux urbains disponibles' }, { label: 'Communes', href: '/communes', detail: 'Niveaux communaux disponibles' }] },
  secteurs: { title: 'Secteurs', section: 'Organisation territoriale', description: 'Préparez le découpage des communes en secteurs.', status: 'Référentiel à compléter', links: [{ label: 'Communes', href: '/communes', detail: 'Gérer le niveau parent' }] },
  chefferies: { title: 'Chefferies', section: 'Organisation territoriale', description: 'Préparez le référentiel des chefferies et leur rattachement territorial.', status: 'Référentiel à compléter', links: [{ label: 'Communes', href: '/communes', detail: 'Gérer le niveau parent' }] },
  groupements: { title: 'Groupements', section: 'Organisation territoriale', description: 'Préparez le référentiel des groupements coutumiers.', status: 'Référentiel à compléter', links: [{ label: 'Communes', href: '/communes', detail: 'Gérer le niveau parent' }] },
  villages: { title: 'Villages', section: 'Organisation territoriale', description: 'Préparez le référentiel des villages et leur rattachement.', status: 'Référentiel à compléter', links: [{ label: 'Communes', href: '/communes', detail: 'Gérer le niveau parent' }] },
  affectations: { title: 'Affectations', section: 'Gestion administrative', description: 'Suivez les affectations et rattachements des agents.', status: 'Opérations agents', links: [{ label: 'Ouvrir les agents', href: '/agents', detail: 'Sélectionner un dossier agent' }, { label: 'Historique des mouvements', href: '/modules/mouvements', detail: 'Consulter les mouvements' }] },
  mouvements: { title: 'Historique des mouvements', section: 'Gestion administrative', description: 'Centralisez les changements d’affectation et mouvements administratifs.', status: 'Opérations agents', links: [{ label: 'Ouvrir le workflow', href: '/workflows', detail: 'Dossiers en cours' }, { label: 'Ouvrir les agents', href: '/agents', detail: 'Accéder aux dossiers' }] },
  mutations: { title: 'Mutations', section: 'Gestion administrative', description: 'Préparez les dossiers de mutation des agents.', status: 'Workflow à compléter', links: [{ label: 'Dossiers workflow', href: '/workflows', detail: 'Contrôler les dossiers en cours' }] },
  promotions: { title: 'Promotions', section: 'Gestion administrative', description: 'Préparez les décisions de promotion et leur suivi.', status: 'Workflow à compléter', links: [{ label: 'Grades et fonctions', href: '/grade-stats', detail: 'Consulter les référentiels' }, { label: 'Dossiers workflow', href: '/workflows', detail: 'Suivre les validations' }] },
  transferts: { title: 'Transferts', section: 'Gestion administrative', description: 'Préparez les dossiers de transfert entre structures.', status: 'Workflow à compléter', links: [{ label: 'Dossiers workflow', href: '/workflows', detail: 'Suivre les validations' }] },
  'changements-fonction': { title: 'Changements de fonction', section: 'Gestion administrative', description: 'Suivez les changements de fonction et leurs validations.', status: 'Workflow à compléter', links: [{ label: 'Fonctions', href: '/fonctions', detail: 'Référentiel des fonctions' }, { label: 'Dossiers workflow', href: '/workflows', detail: 'Suivre les validations' }] },
  'mises-disposition': { title: 'Mises à disposition', section: 'Gestion administrative', description: 'Préparez les dossiers de mise à disposition des agents.', status: 'Workflow à compléter', links: [{ label: 'Dossiers workflow', href: '/workflows', detail: 'Suivre les validations' }] },
  reintegrations: { title: 'Réintégrations', section: 'Gestion administrative', description: 'Préparez les dossiers de réintégration après une interruption.', status: 'Workflow à compléter', links: [{ label: 'Dossiers workflow', href: '/workflows', detail: 'Suivre les validations' }] },
  'dossiers-recus': { title: 'Dossiers reçus', section: 'Circuit administratif / workflow', description: 'Consultez les dossiers transmis à votre périmètre de traitement.', status: 'File workflow', links: [{ label: 'Ouvrir le workflow', href: '/workflows', detail: 'Consulter les dossiers' }] },
  'dossiers-a-traiter': { title: 'Dossiers à traiter', section: 'Circuit administratif / workflow', description: 'Traitez les dossiers qui attendent une action administrative.', status: 'File workflow', links: [{ label: 'Ouvrir le workflow', href: '/workflows', detail: 'Traiter les dossiers' }] },
  'dossiers-transmis': { title: 'Dossiers transmis', section: 'Circuit administratif / workflow', description: 'Suivez les dossiers envoyés vers l’étape administrative suivante.', status: 'File workflow', links: [{ label: 'Ouvrir le workflow', href: '/workflows', detail: 'Suivre les transmissions' }] },
  'dossiers-retournes': { title: 'Dossiers retournés', section: 'Circuit administratif / workflow', description: 'Identifiez les dossiers retournés pour correction ou complément.', status: 'File workflow', links: [{ label: 'Ouvrir le workflow', href: '/workflows', detail: 'Corriger les dossiers' }] },
  'dossiers-valides': { title: 'Dossiers validés', section: 'Circuit administratif / workflow', description: 'Consultez les dossiers ayant terminé leur validation.', status: 'File workflow', links: [{ label: 'Ouvrir le workflow', href: '/workflows', detail: 'Consulter les validations' }] },
  'mes-dossiers': { title: 'Mes dossiers', section: 'Circuit administratif / workflow', description: 'Retrouvez les dossiers affectés à votre espace de travail.', status: 'File workflow', links: [{ label: 'Ouvrir le workflow', href: '/workflows', detail: 'Consulter vos dossiers' }] },
  historique: { title: 'Historique du circuit', section: 'Circuit administratif / workflow', description: 'Suivez les étapes et décisions enregistrées dans le circuit.', status: 'Historique workflow', links: [{ label: 'Ouvrir le workflow', href: '/workflows', detail: 'Consulter l’historique' }] },
  'courriers-entrants': { title: 'Courriers entrants', section: 'Courriers', description: 'Enregistrez et orientez les courriers reçus par l’administration.', status: 'Registre à compléter', links: [{ label: 'Documents administratifs', href: '/documents', detail: 'Consulter les pièces' }, { label: 'Dossiers à traiter', href: '/modules/courriers-a-traiter', detail: 'Suivre le traitement' }] },
  'courriers-sortants': { title: 'Courriers sortants', section: 'Courriers', description: 'Préparez le registre des courriers envoyés par l’administration.', status: 'Registre à compléter', links: [{ label: 'Documents administratifs', href: '/documents', detail: 'Consulter les pièces' }] },
  'courriers-internes': { title: 'Courriers internes', section: 'Courriers', description: 'Organisez les échanges internes entre directions et services.', status: 'Registre à compléter', links: [{ label: 'Documents administratifs', href: '/documents', detail: 'Consulter les pièces' }] },
  'courriers-a-traiter': { title: 'Courriers à traiter', section: 'Courriers', description: 'Centralisez les courriers nécessitant une action ou une réponse.', status: 'File de traitement', links: [{ label: 'Ouvrir le workflow', href: '/workflows', detail: 'Suivre les actions' }] },
  'archives-courriers': { title: 'Archives des courriers', section: 'Courriers', description: 'Préparez la consultation des courriers clôturés et archivés.', status: 'Archivage à compléter', links: [{ label: 'Documents administratifs', href: '/documents', detail: 'Consulter les pièces' }] },
  categories: { title: 'Catégories', section: 'Grades et fonctions', description: 'Préparez le classement des agents par catégories administratives.', status: 'Référentiel à compléter', links: [{ label: 'Grades', href: '/grade-stats', detail: 'Consulter les grades' }, { label: 'Fonctions', href: '/fonctions', detail: 'Consulter les fonctions' }] },
  'scanner-materiel': { title: 'Scanner matériel', section: 'Documents et archives', description: 'Point d’entrée pour les documents numérisés depuis un scanner.', status: 'Capture à connecter', links: [{ label: 'Importer un document', href: '/documents', detail: 'Déposer un fichier existant' }] },
  'scanner-camera': { title: 'Scanner caméra', section: 'Documents et archives', description: 'Point d’entrée pour les captures de documents depuis une caméra.', status: 'Capture à connecter', links: [{ label: 'Importer un document', href: '/documents', detail: 'Déposer un fichier existant' }] },
  'import-document': { title: 'Importer un document', section: 'Documents et archives', description: 'Préparez l’import et le classement des pièces administratives.', status: 'Import disponible dans Documents', links: [{ label: 'Ouvrir Documents', href: '/documents', detail: 'Consulter les documents existants' }] },
  classement: { title: 'Documents à classer', section: 'Documents et archives', description: 'Espace de traitement des documents en attente de classement.', status: 'Classement à compléter', links: [{ label: 'Ouvrir Documents', href: '/documents', detail: 'Consulter les documents disponibles' }] },
  archives: { title: 'Archives', section: 'Documents et archives', description: 'Préparez la consultation des documents archivés.', status: 'Archivage à compléter', links: [{ label: 'Ouvrir Documents', href: '/documents', detail: 'Consulter les documents' }] },
  retards: { title: 'Retards', section: 'Présences et temps', description: 'Suivez les retards à partir du journal des présences.', status: 'Filtre de présence', links: [{ label: 'Journal des présences', href: '/presence/journal', detail: 'Consulter les pointages' }] },
  absences: { title: 'Absences', section: 'Présences et temps', description: 'Suivez les absences à partir du journal des présences.', status: 'Filtre de présence', links: [{ label: 'Journal des présences', href: '/presence/journal', detail: 'Consulter les pointages' }] },
  'conges-demandes': { title: 'Demandes de congé', section: 'Congés et absences', description: 'Préparez l’enregistrement et le suivi des demandes de congé.', status: 'Workflow à compléter', links: [{ label: 'Dossiers workflow', href: '/workflows', detail: 'Suivre les demandes' }] },
  'conges-en-cours': { title: 'Congés en cours', section: 'Congés et absences', description: 'Consultez les congés actuellement suivis par le circuit administratif.', status: 'Workflow à compléter', links: [{ label: 'Dossiers workflow', href: '/workflows', detail: 'Suivre les dossiers' }] },
  'conges-historique': { title: 'Historique des congés', section: 'Congés et absences', description: 'Préparez la consultation de l’historique des congés.', status: 'Historique à compléter', links: [{ label: 'Dossiers workflow', href: '/workflows', detail: 'Consulter les dossiers traités' }] },
  missions: { title: 'Missions', section: 'Congés et absences', description: 'Préparez le suivi des missions administratives.', status: 'Workflow à compléter', links: [{ label: 'Dossiers workflow', href: '/workflows', detail: 'Suivre les validations' }] },
  autorisations: { title: 'Autorisations', section: 'Congés et absences', description: 'Préparez le suivi des autorisations administratives.', status: 'Workflow à compléter', links: [{ label: 'Dossiers workflow', href: '/workflows', detail: 'Suivre les validations' }] },
};

export default function ModulePage() {
  const params = useParams<{ module: string }>();
  const moduleKey = String(params.module || '');
  const readableName = moduleKey.replace(/-/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
  const module = moduleCatalog[moduleKey] || {
    title: readableName || 'Module SIGAD',
    section: moduleKey.startsWith('rapport-') || moduleKey === 'export-rapports' ? 'Rapports et statistiques' : 'Administration',
    description: 'Cet espace métier regroupe le contexte et les accès associés à cette rubrique.',
    status: 'Configuration à compléter',
    links: [{ label: 'Retour au tableau de bord', href: '/', detail: 'Revenir au pilotage' }, { label: 'Rapports généraux', href: '/reports', detail: 'Consulter les indicateurs disponibles' }],
  };

  return <div className="office-layout"><OfficeHeader /><div className="office-body"><OfficeSidebar /><main className="office-content module-workspace"><div className="module-breadcrumb">SIGAD · {module.section}</div><div className="module-hero"><div><span className="module-kicker"><Settings2 size={15} /> Espace métier</span><h1>{module.title}</h1><p>{module.description}</p></div><span className="module-state"><CheckCircle2 size={15} /> {module.status}</span></div><section className="module-grid"><article className="module-info-card"><span className="module-card-icon"><ClipboardList size={20} /></span><h2>Fonctionnement du module</h2><p>Cette entrée du menu possède maintenant un espace dédié. Les opérations rattachées sont regroupées ci-dessous pour garder un parcours clair et éviter les redirections ambiguës.</p></article><article className="module-info-card"><span className="module-card-icon"><FileText size={20} /></span><h2>Accès associés</h2><p>Utilisez les accès existants pour poursuivre le traitement des dossiers.</p><div className="module-links">{module.links.map((link) => <Link href={link.href} key={link.href + link.label}><span><strong>{link.label}</strong><small>{link.detail}</small></span><ArrowRight size={16} /></Link>)}</div></article></section></main></div></div>;
}
